import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { compression } from 'vite-plugin-compression2';

export default defineConfig({
	plugins: [
		sveltekit(),
		compression({ algorithms: ['gzip', 'brotliCompress'], exclude: [/\.(br|gz)$/] }),
	],
	server: {
		proxy: {
			'/api': 'http://localhost:3000',
			'/ws': { target: 'ws://localhost:3000', ws: true },
		}
	},
	optimizeDeps: {
		include: [
			'lucide-svelte/icons/calendar',
			'lucide-svelte/icons/calendar-days',
			'lucide-svelte/icons/check-square',
			'lucide-svelte/icons/chevron-left',
			'lucide-svelte/icons/chevron-right',
			'lucide-svelte/icons/clock',
			'lucide-svelte/icons/eye',
			'lucide-svelte/icons/link',
			'lucide-svelte/icons/loader',
			'lucide-svelte/icons/log-out',
			'lucide-svelte/icons/chevron-up',
			'lucide-svelte/icons/map-pin',
			'lucide-svelte/icons/menu',
			'lucide-svelte/icons/panel-left-close',
			'lucide-svelte/icons/panel-left-open',
			'lucide-svelte/icons/refresh-cw',
			'lucide-svelte/icons/repeat',
			'lucide-svelte/icons/search',
			'lucide-svelte/icons/settings',
			'lucide-svelte/icons/target',
			'lucide-svelte/icons/trash-2',
			'lucide-svelte/icons/triangle-alert',
			'lucide-svelte/icons/users',
			'lucide-svelte/icons/x',
			'lucide-svelte/icons/bar-chart-3',
			'lucide-svelte/icons/download',
			'lucide-svelte/icons/ellipsis-vertical',
			'lucide-svelte/icons/history',
			'lucide-svelte/icons/arrow-right',
			'lucide-svelte/icons/plus',
			'lucide-svelte/icons/chevrons-up-down',
			'lucide-svelte/icons/wifi',
			'lucide-svelte/icons/wifi-off',
			'lucide-svelte/icons/pencil',
			'lucide-svelte/icons/lock',
			'lucide-svelte/icons/unlock',
			'lucide-svelte/icons/bell',
			'lucide-svelte/icons/bell-off',
			'lucide-svelte/icons/flame',
			'lucide-svelte/icons/link-2',
			'lucide-svelte/icons/circle-check',
			'lucide-svelte/icons/eye-off',
			'lucide-svelte/icons/user',
			'lucide-svelte/icons/check',
			'lucide-svelte/icons/loader-2',
			'lucide-svelte/icons/gauge',
			'lucide-svelte/icons/list-checks',
			'lucide-svelte/icons/check-circle',
			'lucide-svelte/icons/alert-circle',
			'lucide-svelte/icons/mail',
			'lucide-svelte/icons/file-text',
			'lucide-svelte/icons/shield',
			'lucide-svelte/icons/monitor',
			'lucide-svelte/icons/toggle-left',
			'lucide-svelte/icons/toggle-right',
			'lucide-svelte/icons/dumbbell',
			'lucide-svelte/icons/book-open',
			'lucide-svelte/icons/brain',
			'lucide-svelte/icons/clipboard-list',
			'lucide-svelte/icons/languages',
		],
	},
	build: {
		cssMinify: 'lightningcss',
		minify: 'esbuild',
		target: 'es2020',
	},
	esbuild: {
		drop: ['console', 'debugger'],
		legalComments: 'none',
	},
});
